development:
  adapter: redis
  url: redis://redis-01:6379/1

test:
  adapter: redis
  url: redis://redis-01:6379/1

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: zpub-api_production
