development:
  clients:
    default:
      database: zpub_api_development
      hosts:
        - mongo-01:27017
      options:
  options:
    include_root_in_json: true
    include_type_for_serialization: true
    app_name: ZPub API
    raise_not_found_error: false

test:
  clients:
    default:
      database: zpub_api_test
      hosts:
        - mongo-01:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
    raise_not_found_error: false
